{
 "title": "Aquarium Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "InfluxDB", "query": "influxdb" },
   { "name": "alkChange", "label": "Last Alk Change", "query": "1650394800000000000" },
   { "name": "caChange", "label": "caChange", "query": "1649375085161000000" },
   { "name": "mgChange", "label": "mgChange", "query": "1649907000000000000" },
   { "name": "BigBottle", "label": "Big Red Sea Bottle", "query": "1000" },
   { "name": "SmallBottle", "query": "500" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "farenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tmp" }
     ]
    }
   ]
  },
  {
   "title": "Aquarium Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "farenheit" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "Temp" }
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "pH" }
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "pH" }
     ]
    }
   ]
  },
  {
   "title": "Apex Alert",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "EmailAlrt" }
     ]
    }
   ]
  },
  {
   "title": "Return Chamber LOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "SUMPLOW" }
     ]
    }
   ]
  },
  {
   "title": "ATO Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apex_inputs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ATO_LO" }
     ]
    }
   ]
  },
  {
   "title": "Refugium Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apex_inputs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ATO_LO" }
     ]
    }
   ]
  },
  {
   "title": "Alkalinity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Alkx6" }
     ]
    }
   ]
  },
  {
   "title": "Alk Dose Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apex_dosing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Calcium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Cax6" }
     ]
    }
   ]
  },
  {
   "title": "Ca Dose Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apex_dosing",
     "query": "SELECT sum(\"value\") FROM \"apex_dosing\" WHERE (\"did\" = '7_2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_2" }
     ]
    }
   ]
  },
  {
   "title": "Magnesium",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Mgx6" }
     ]
    }
   ]
  },
  {
   "title": "Mg Dose Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apex_dosing",
     "query": "SELECT sum(\"value\") FROM \"apex_dosing\" WHERE (\"did\" = '8_1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Power Draw - Total",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "apex_inputs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pwr" }
     ]
    }
   ]
  },
  {
   "title": "ATO Outlet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_1" }
     ]
    }
   ]
  },
  {
   "title": "Cabinet Lights Outlet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_3" }
     ]
    }
   ]
  },
  {
   "title": "Heater Outlet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_4" }
     ]
    }
   ]
  },
  {
   "title": "UV Sterilizer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_2" }
     ]
    }
   ]
  },
  {
   "title": "Skimmer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_5" }
     ]
    }
   ]
  },
  {
   "title": "Skimmer Fresh Air Valve",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_10" }
     ]
    }
   ]
  },
  {
   "title": "Alk Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apex_dosing",
     "query": "SELECT ($BigBottle-sum(\"value\")) FROM \"apex_dosing\" WHERE (\"did\" = '7_1') AND time >= $alkChange",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Ca Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apex_dosing",
     "query": "SELECT ($BigBottle-sum(\"value\")) FROM \"apex_dosing\" WHERE (\"did\" = '7_2') AND time >= $caChange",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Mg Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apex_dosing",
     "query": "SELECT ($BigBottle-sum(\"value\")) FROM \"apex_dosing\" WHERE (\"did\" = '8_1') AND time >= $mgChange",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Return Pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_6" }
     ]
    }
   ]
  },
  {
   "title": "Wave Pump 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_8" }
     ]
    }
   ]
  },
  {
   "title": "Wave Pump 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "2_7" }
     ]
    }
   ]
  },
  {
   "title": "Alk Dose Pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "7_1" }
     ]
    }
   ]
  },
  {
   "title": "Ca Dose Pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "7_2" }
     ]
    }
   ]
  },
  {
   "title": "Mg Dose Pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_id", "operator": "=", "value": "8_1" }
     ]
    }
   ]
  },
  {
   "title": "Waste Container",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/1900*100", "type": "math" }
   ]
  },
  {
   "title": "Reagent A",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/250*100", "type": "math" }
   ]
  },
  {
   "title": "Reagent B",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/250*100", "type": "math" }
   ]
  },
  {
   "title": "Reagent C",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/250*100", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "options": {
    "content": "<h2><center>Virtual Outlets</center><h2>"
   }
  },
  {
   "title": "Red Light",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RedLight" }
     ]
    }
   ]
  },
  {
   "title": "Alkalinity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dKh" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "alk" }
     ]
    }
   ]
  },
  {
   "title": "Calcium PPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "Calcium",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "ca" }
     ]
    }
   ]
  },
  {
   "title": "Magnesium PPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "mg" }
     ]
    }
   ]
  },
  {
   "title": "Cabinet Light Monitor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "CABLED_MTR" }
     ]
    }
   ]
  },
  {
   "title": "Refugium Monitor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Refugium_MTR" }
     ]
    }
   ]
  },
  {
   "title": "Return Pump 8%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "SetPump8" }
     ]
    }
   ]
  },
  {
   "title": "Return Pump 15%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "SetPumpLowFl" }
     ]
    }
   ]
  },
  {
   "title": "Power Draw - By Device",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "apex_inputs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pwr" }
     ]
    }
   ]
  },
  {
   "title": "Dosing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Alkalinity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apex_dosing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_1" }
     ]
    },
    {
     "alias": "Calcium",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apex_dosing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "7_2" }
     ]
    },
    {
     "alias": "Magnesium",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apex_dosing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=", "value": "8_1" }
     ]
    }
   ]
  },
  {
   "title": "Power Draw - By Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "apex_inputs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pwr" }
     ]
    }
   ]
  },
  { "title": "Events", "type": "annolist", "gridPos": { "h": 24, "w": 18, "x": 0, "y": 33 } }
 ]
}